### ISSUE TITLE
Not all functions understand "nthreads" argument + more documentation please

### ISSUE THREAD

**Issue by tony-aw** [traversc/stringfish#17]
Hi traversc,

First of all, well done with the stringfish R package. I like it. I do have 2 small issues.

**First issue:**
Not a huge issue per-sé, but I noticed that some functions do have a "nthreads" argument, yet if you specify this argument, it raises an error. Consider for example the following piece of code:
`
> s <- "hello"
> sf_substr(s, 1,3, nthreads = 2)
[1] "hel"
> sf_nchar(s, 1,3, nthreads = 2)
Error in sf_nchar(s, 1, 3, nthreads = 2) : unused argument (3)
`

Both `sf_nchar()` and `sf_substr()` are supposed to have a `nthreads` argument, yet as shown in the above code, it works in `sf_substr()`, but not in `sf_nchar()`. Am I doing something wrong? Or is this a mistake in the `stringfish` package?

**Second issue:**
I have another issue, though it might be a matter of "taste": the documentation and vignette for stringfish is somewhat minimal. Could you perhaps expand the documentation please?
Things that you might want to consider to add to your documentation are the following:

- Is the "pattern" argument in sf_grepl vectorized, or must it be a single string pattern (I know one can figure this out oneself, but proper documentation is, I think, preferable).
- when is it beneficial to use multiple threads instead of 1 (i.e. what order of magnitude should the character vector be to justify multi-threading for speed advantages).
- efficiency (speed & memory usage) comparison between stringfish and stringi.

Thank you in advance.

Kind regards,

Tony

**Comment by traversc** [comment]
Hi Tony, thanks for your feedback!

For the first issue, I will look into it. 

For sf_grepl the pattern is not vectorized, it mirrors what happens in regular grepl. I'll add some additional documentation to make that clear. 

In my opinion, the main place you could see benefit for (multithreading and in general) is in applying regex to large vectors. 

Stringfish vs stringi:

The main difference in stringfish is the use of ALT-REP, which means creation of new strings is much faster, so operations that create new strings are generally faster than stringi. Other popular packages use this approach (vroom and arrow). 

I also use stringi/stringr quite frequently and it is much, much more comprehensive. Ideally, I'd be interested in seeing stringi converted to an ALT-REP framework (which would be easier than expanding the scope of stringfish to be as comprehensive) but there doesn't seem to be too much interest in doing so.

**Comment by tony-aw** [comment]
Thank you for your response!

**Comment by tony-aw** [comment]
Hi traversc,

I see that this issue has not yet been closed. Have you found the time to look at the issue regarding the `nthreads` argument?

Kind regards,

Tony

**Comment by traversc** [comment]
In your example, you have too many arguments:

```
s <- "hello"
sf_nchar(s, 1,3, nthreads = 2)
```

Try this instead:
```
s <- "hello"
sf_nchar(s, nthreads = 2)
```

Best,
Travers
