### ISSUE TITLE
error: ‘atomic’ is not a member of ‘tbb’

### ISSUE THREAD

**Issue by IgnatiusPang** [traversc/stringfish#19]
Dear Package Developer,

Please give me some advice on how to install the package on CentOS 7, with the following error message?

> install.packages("stringfish", type="source", configure.args="--with-simd=AVX2")
Installing package into ‘/home/ipang/R/x86_64-pc-linux-gnu-library/4.2’
(as ‘lib’ is unspecified)
trying URL 'https://cran.rstudio.com/src/contrib/stringfish_0.15.7.tar.gz'
Content type 'application/x-gzip' length 1156305 bytes (1.1 MB)
==================================================
downloaded 1.1 MB

* installing *source* package ‘stringfish’ ...
** package ‘stringfish’ successfully unpacked and MD5 sums checked
** using staged installation
checking for pkg-config... /usr/bin/pkg-config
stringfish configure script
PCRE2 10.23 library detected but is lower than bundled version (10.35) -- compiling from source
Using AVX2

-IPCRE2 -mavx2 -msse3 -msse2
$(LIBPCRE2)
configure: creating ./config.status
config.status: creating src/Makevars
** libs
g++ -std=gnu++11 -I"/opt/R/4.2.2/lib/R/include" -DNDEBUG -DRCPP_USE_UNWIND_PROTECT -DRCPP_NO_RTTI -DPCRE2_CODE_UNIT_WIDTH=8 -DHAVE_CONFIG_H -DPCRE2_BUNDLED -I.  -IPCRE2 -mavx2 -msse3 -msse2 -I'/home/ipang/R/x86_64-pc-linux-gnu-library/4.2/Rcpp/include' -I'/home/ipang/R/x86_64-pc-linux-gnu-library/4.2/RcppParallel/include' -I/usr/local/include   -fpic  -g -O2  -c RcppExports.cpp -o RcppExports.o
g++ -std=gnu++11 -I"/opt/R/4.2.2/lib/R/include" -DNDEBUG -DRCPP_USE_UNWIND_PROTECT -DRCPP_NO_RTTI -DPCRE2_CODE_UNIT_WIDTH=8 -DHAVE_CONFIG_H -DPCRE2_BUNDLED -I.  -IPCRE2 -mavx2 -msse3 -msse2 -I'/home/ipang/R/x86_64-pc-linux-gnu-library/4.2/Rcpp/include' -I'/home/ipang/R/x86_64-pc-linux-gnu-library/4.2/RcppParallel/include' -I/usr/local/include   -fpic  -g -O2  -c sf_functions.cpp -o sf_functions.o
sf_functions.cpp:1351:85: error: ‘atomic’ is not a member of ‘tbb’
 using tbb_rstring_map = tbb::concurrent_unordered_map<RStringIndexer::rstring_info, tbb::atomic<int>, rstring_info_hash>;
                                                                                     ^
sf_functions.cpp:1351:85: note: suggested alternative:
In file included from /usr/include/c++/4.8.2/atomic:41:0,
                 from /home/ipang/R/x86_64-pc-linux-gnu-library/4.2/RcppParallel/include/oneapi/tbb/detail/_utils.h:22,
                 from /home/ipang/R/x86_64-pc-linux-gnu-library/4.2/RcppParallel/include/oneapi/tbb/detail/_range_common.h:21,
                 from /home/ipang/R/x86_64-pc-linux-gnu-library/4.2/RcppParallel/include/oneapi/tbb/blocked_range.h:22,
                 from /home/ipang/R/x86_64-pc-linux-gnu-library/4.2/RcppParallel/include/tbb/../oneapi/tbb.h:28,
                 from /home/ipang/R/x86_64-pc-linux-gnu-library/4.2/RcppParallel/include/tbb/tbb.h:17,
                 from /home/ipang/R/x86_64-pc-linux-gnu-library/4.2/RcppParallel/include/RcppParallel/TBB.h:10,
                 from /home/ipang/R/x86_64-pc-linux-gnu-library/4.2/RcppParallel/include/RcppParallel.h:21,
                 from sf_functions.cpp:2:
/usr/include/c++/4.8.2/bits/atomic_base.h:237:12: note:   ‘std::atomic’
     struct atomic;
            ^
sf_functions.cpp:1351:85: error: ‘atomic’ is not a member of ‘tbb’
 using tbb_rstring_map = tbb::concurrent_unordered_map<RStringIndexer::rstring_info, tbb::atomic<int>, rstring_info_hash>;
                                                                                     ^
sf_functions.cpp:1351:85: note: suggested alternative:
In file included from /usr/include/c++/4.8.2/atomic:41:0,
                 from /home/ipang/R/x86_64-pc-linux-gnu-library/4.2/RcppParallel/include/oneapi/tbb/detail/_utils.h:22,
                 from /home/ipang/R/x86_64-pc-linux-gnu-library/4.2/RcppParallel/include/oneapi/tbb/detail/_range_common.h:21,
                 from /home/ipang/R/x86_64-pc-linux-gnu-library/4.2/RcppParallel/include/oneapi/tbb/blocked_range.h:22,
                 from /home/ipang/R/x86_64-pc-linux-gnu-library/4.2/RcppParallel/include/tbb/../oneapi/tbb.h:28,
                 from /home/ipang/R/x86_64-pc-linux-gnu-library/4.2/RcppParallel/include/tbb/tbb.h:17,
                 from /home/ipang/R/x86_64-pc-linux-gnu-library/4.2/RcppParallel/include/RcppParallel/TBB.h:10,
                 from /home/ipang/R/x86_64-pc-linux-gnu-library/4.2/RcppParallel/include/RcppParallel.h:21,
                 from sf_functions.cpp:2:
/usr/include/c++/4.8.2/bits/atomic_base.h:237:12: note:   ‘std::atomic’
     struct atomic;
            ^
sf_functions.cpp:1351:100: error: template argument 2 is invalid
 using tbb_rstring_map = tbb::concurrent_unordered_map<RStringIndexer::rstring_info, tbb::atomic<int>, rstring_info_hash>;
                                                                                                    ^
sf_functions.cpp:1351:100: error: template argument 5 is invalid
sf_functions.cpp:1354:3: error: ‘tbb_rstring_map’ does not name a type
   tbb_rstring_map * table_hash;
   ^
sf_functions.cpp:1356:36: error: expected ‘)’ before ‘*’ token
   hash_fill_worker(tbb_rstring_map * t, RStringIndexer * f) : 
                                    ^
sf_functions.cpp: In member function ‘virtual void hash_fill_worker::operator()(std::size_t, std::size_t)’:
sf_functions.cpp:1362:16: error: ‘table_hash’ was not declared in this scope
       auto p = table_hash->insert(tbb_rstring_map::value_type(q,i));
                ^
sf_functions.cpp:1362:35: error: ‘tbb_rstring_map’ has not been declared
       auto p = table_hash->insert(tbb_rstring_map::value_type(q,i));
                                   ^
sf_functions.cpp: At global scope:
sf_functions.cpp:1375:3: error: ‘tbb_rstring_map’ does not name a type
   tbb_rstring_map * table_hash;
   ^
sf_functions.cpp:1378:38: error: expected ‘)’ before ‘*’ token
   hash_search_worker(tbb_rstring_map * t, RStringIndexer * s, int * o) : 
                                      ^
sf_functions.cpp: In member function ‘virtual void hash_search_worker::operator()(std::size_t, std::size_t)’:
sf_functions.cpp:1384:17: error: ‘table_hash’ was not declared in this scope
       auto it = table_hash->find(q);
                 ^
sf_functions.cpp: In function ‘Rcpp::IntegerVector sf_match(SEXP, SEXP, int)’:
sf_functions.cpp:1408:5: error: ‘tbb_rstring_map’ was not declared in this scope
     tbb_rstring_map table_hash;
     ^
sf_functions.cpp:1408:21: error: expected ‘;’ before ‘table_hash’
     tbb_rstring_map table_hash;
                     ^
sf_functions.cpp:1409:26: error: ‘table_hash’ was not declared in this scope
     hash_fill_worker w1(&table_hash, &cr);
                          ^
make: *** [sf_functions.o] Error 1
ERROR: compilation failed for package ‘stringfish’
* removing ‘/home/ipang/R/x86_64-pc-linux-gnu-library/4.2/stringfish’
Warning in install.packages :
  installation of package ‘stringfish’ had non-zero exit status

The downloaded source packages are in
	‘/tmp/RtmpOB60TC/downloaded_packages’

**Comment by traversc** [comment]
Hi Thanks for the report. 

What is the version of RcppParallel `packageVersion("RcppParallel")` ? And does updating that help?

**Comment by IgnatiusPang** [comment]
> packageVersion("RcppParallel")
[1] ‘5.1.7.9000’

Updating does not seems to help, same error.

**Comment by traversc** [comment]
Hello, please try out the latest version on github and let me know: `devtools::install_github("traversc/stringfish")`.
