### ISSUE TITLE
Fails to Build on Ubuntu 18 and 20

### ISSUE THREAD

**Issue by kzscisoft** [traversc/stringfish#4]
I noticed the CI included with this repository is Ubuntu "Trusty" 14. The project I am working on uses the package "qs" which uses "stringfish" during the install. Prior to the recent update to version 0.13.3 installation of this package under GitHub actions using Ubuntu 18 was successful, however with the recent changes I now the following error:

```
Error: package or namespace load failed for ‘stringfish’:
 .onAttach failed in attachNamespace() for 'stringfish', details:
  call: if (utils::localeToCharset()[1] == "UTF-8") set_is_utf8_locale()
  error: missing value where TRUE/FALSE needed
Error: loading failed
Execution halted
ERROR: loading failed
```

If I run the command:

```
library(utils)
utils::localeToCharset()[1] == "UTF-8"
```
within R itself I do not encounter any issues.

**Comment by traversc** [comment]
For `qs` you can use `remotes::install_github("traversc/qs@legacy")` for now. 

I'm also using Ubuntu 20, and don't understand why you get that error, especially if you can run the command in R, but I'll add some safeguards to fallback on in the next CRAN version.

**Comment by nicholasdavies** [comment]
I got this same error, which was preventing me from deploying an app that uses `qs` to shinyapps.io; perhaps testing on that platform would allow devs to reproduce this error? 

The fix suggested by @traversc has resolved the issue for now though, thanks!

**Comment by achubaty** [comment]
@traversc FYI on e.g. a desktop version of Ubuntu this isn't an issue because a UTF8 locale is typically set. However, in CI environments like travis and github actions, a default C locale is used.

I can get around this error in some cases by simply settng a utf8 locale:

```
sudo locale-gen en_CA.UTF-8
sudo update-locale LANG=en_CA.UTF-8
```

But even this usually requires a reboot to take effect everywhere. Not sure how to get new locale settings without reboot on these CI machines.

**Comment by achubaty** [comment]
after a bit more work, I can confirm that the latest github version (0.14.1) works on github actions. thank you!

**Comment by traversc** [comment]
Thanks for the information! (Even with a "C" locale, I'm surprised the functions returns "NA").
