### ISSUE TITLE
shared object ‘stringfish.so’ not found

### ISSUE THREAD

**Issue by MelvinGatMDRC** [traversc/stringfish#6]
Received the following error when attempting to install `stringfish` in R 4.0.4:
  
    Error: package or namespace load failed for ‘stringfish’ in library.dynam(lib, package, package.lib):
 shared object ‘stringfish.so’ not found
  
Used the following `install.packages()` call from the [`stringfish` README](https://github.com/traversc/stringfish):
  
     install.packages("stringfish", type="source", configure.args="--with-simd=AVX2")
  
Also occurs when using a vanilla `install.packages("stringfish")` call as well. 

Not sure what else might be helpful.

**Comment by traversc** [comment]
Can you print out the full log after `install.packages`? And what is the operating system?

**Comment by MelvinGatMDRC** [comment]
Thanks for the quick response. Operating system is Red Hat 8. Log below. 

install.packages("stringfish", type="source", configure.args="--with-simd=AVX2")
Installing package into ‘/home/user/R/x86_64-pc-linux-gnu-library/4.0.4’
(as ‘lib’ is unspecified)
trying URL 'https://mran.revolutionanalytics.com/snapshot/2021-03-06/src/contrib/stringfish_0.15.0.tar.gz'
Content type 'application/octet-stream' length 1275870 bytes (1.2 MB)
==================================================
downloaded 1.2 MB

* installing *source* package ‘stringfish’ ...
** package ‘stringfish’ successfully unpacked and MD5 sums checked
** using staged installation
checking for pkg-config... /usr/bin/pkg-config
stringfish configure script
PCRE2 10.32 dynamic library detected but is lower than bundled version (10.35) -- compiling from source
Using AVX2
-L. -lSFPCRE2
-DPCRE2_CODE_UNIT_WIDTH=8 -DHAVE_CONFIG_H -IPCRE2 -mavx2 -msse3 -msse2
LIBPCRE2 = PCRE2/pcre2_chartables.o \ PCRE2/pcre2_auto_possess.o \ PCRE2/pcre2_compile.o \ PCRE2/pcre2_config.o \ PCRE2/pcre2_context.o \ PCRE2/pcre2_convert.o \ PCRE2/pcre2_dfa_match.o \ PCRE2/pcre2_error.o \ PCRE2/pcre2_extuni.o \ PCRE2/pcre2_find_bracket.o \ PCRE2/pcre2_jit_compile.o \ PCRE2/pcre2_maketables.o \ PCRE2/pcre2_match.o \ PCRE2/pcre2_match_data.o \ PCRE2/pcre2_newline.o \ PCRE2/pcre2_ord2utf.o \ PCRE2/pcre2_pattern_info.o \ PCRE2/pcre2_script_run.o \ PCRE2/pcre2_serialize.o \ PCRE2/pcre2_string_utils.o \ PCRE2/pcre2_study.o \ PCRE2/pcre2_substitute.o \ PCRE2/pcre2_substring.o \ PCRE2/pcre2_tables.o \ PCRE2/pcre2_ucd.o \ PCRE2/pcre2_valid_utf.o \ PCRE2/pcre2_xclass.o $(SHLIB): libSFPCRE2.a libSFPCRE2.a: $(LIBPCRE2) $(AR) rcs libSFPCRE2.a $(LIBPCRE2) clean: rm -f $(SHLIB) $(OBJECTS) $(LIBPCRE2) libSFPCRE2.a

configure: creating ./config.status
config.status: creating src/Makevars
** libs
g++ -std=gnu++11 -I"/opt/R/4.0.4/lib/R/include" -DNDEBUG -DRCPP_USE_UNWIND_PROTECT -I.  -DPCRE2_CODE_UNIT_WIDTH=8 -DHAVE_CONFIG_H -IPCRE2 -mavx2 -msse3 -msse2 -I'/opt/R/4.0.4/lib/R/site-library/Rcpp/include' -I'/opt/R/4.0.4/lib/R/site-library/RcppParallel/include' -I/usr/local/include   -fpic  -g -O2  -c RcppExports.cpp -o RcppExports.o
g++ -std=gnu++11 -I"/opt/R/4.0.4/lib/R/include" -DNDEBUG -DRCPP_USE_UNWIND_PROTECT -I.  -DPCRE2_CODE_UNIT_WIDTH=8 -DHAVE_CONFIG_H -IPCRE2 -mavx2 -msse3 -msse2 -I'/opt/R/4.0.4/lib/R/site-library/Rcpp/include' -I'/opt/R/4.0.4/lib/R/site-library/RcppParallel/include' -I/usr/local/include   -fpic  -g -O2  -c sf_functions.cpp -o sf_functions.o
gcc -I"/opt/R/4.0.4/lib/R/include" -DNDEBUG -DRCPP_USE_UNWIND_PROTECT -I.  -DPCRE2_CODE_UNIT_WIDTH=8 -DHAVE_CONFIG_H -IPCRE2 -mavx2 -msse3 -msse2 -I'/opt/R/4.0.4/lib/R/site-library/Rcpp/include' -I'/opt/R/4.0.4/lib/R/site-library/RcppParallel/include' -I/usr/local/include   -fpic  -g -O2  -c PCRE2/pcre2_chartables.c -o PCRE2/pcre2_chartables.o
gcc -I"/opt/R/4.0.4/lib/R/include" -DNDEBUG -DRCPP_USE_UNWIND_PROTECT -I.  -DPCRE2_CODE_UNIT_WIDTH=8 -DHAVE_CONFIG_H -IPCRE2 -mavx2 -msse3 -msse2 -I'/opt/R/4.0.4/lib/R/site-library/Rcpp/include' -I'/opt/R/4.0.4/lib/R/site-library/RcppParallel/include' -I/usr/local/include   -fpic  -g -O2  -c PCRE2/pcre2_auto_possess.c -o PCRE2/pcre2_auto_possess.o
gcc -I"/opt/R/4.0.4/lib/R/include" -DNDEBUG -DRCPP_USE_UNWIND_PROTECT -I.  -DPCRE2_CODE_UNIT_WIDTH=8 -DHAVE_CONFIG_H -IPCRE2 -mavx2 -msse3 -msse2 -I'/opt/R/4.0.4/lib/R/site-library/Rcpp/include' -I'/opt/R/4.0.4/lib/R/site-library/RcppParallel/include' -I/usr/local/include   -fpic  -g -O2  -c PCRE2/pcre2_compile.c -o PCRE2/pcre2_compile.o
gcc -I"/opt/R/4.0.4/lib/R/include" -DNDEBUG -DRCPP_USE_UNWIND_PROTECT -I.  -DPCRE2_CODE_UNIT_WIDTH=8 -DHAVE_CONFIG_H -IPCRE2 -mavx2 -msse3 -msse2 -I'/opt/R/4.0.4/lib/R/site-library/Rcpp/include' -I'/opt/R/4.0.4/lib/R/site-library/RcppParallel/include' -I/usr/local/include   -fpic  -g -O2  -c PCRE2/pcre2_config.c -o PCRE2/pcre2_config.o
gcc -I"/opt/R/4.0.4/lib/R/include" -DNDEBUG -DRCPP_USE_UNWIND_PROTECT -I.  -DPCRE2_CODE_UNIT_WIDTH=8 -DHAVE_CONFIG_H -IPCRE2 -mavx2 -msse3 -msse2 -I'/opt/R/4.0.4/lib/R/site-library/Rcpp/include' -I'/opt/R/4.0.4/lib/R/site-library/RcppParallel/include' -I/usr/local/include   -fpic  -g -O2  -c PCRE2/pcre2_context.c -o PCRE2/pcre2_context.o
gcc -I"/opt/R/4.0.4/lib/R/include" -DNDEBUG -DRCPP_USE_UNWIND_PROTECT -I.  -DPCRE2_CODE_UNIT_WIDTH=8 -DHAVE_CONFIG_H -IPCRE2 -mavx2 -msse3 -msse2 -I'/opt/R/4.0.4/lib/R/site-library/Rcpp/include' -I'/opt/R/4.0.4/lib/R/site-library/RcppParallel/include' -I/usr/local/include   -fpic  -g -O2  -c PCRE2/pcre2_convert.c -o PCRE2/pcre2_convert.o
gcc -I"/opt/R/4.0.4/lib/R/include" -DNDEBUG -DRCPP_USE_UNWIND_PROTECT -I.  -DPCRE2_CODE_UNIT_WIDTH=8 -DHAVE_CONFIG_H -IPCRE2 -mavx2 -msse3 -msse2 -I'/opt/R/4.0.4/lib/R/site-library/Rcpp/include' -I'/opt/R/4.0.4/lib/R/site-library/RcppParallel/include' -I/usr/local/include   -fpic  -g -O2  -c PCRE2/pcre2_dfa_match.c -o PCRE2/pcre2_dfa_match.o
gcc -I"/opt/R/4.0.4/lib/R/include" -DNDEBUG -DRCPP_USE_UNWIND_PROTECT -I.  -DPCRE2_CODE_UNIT_WIDTH=8 -DHAVE_CONFIG_H -IPCRE2 -mavx2 -msse3 -msse2 -I'/opt/R/4.0.4/lib/R/site-library/Rcpp/include' -I'/opt/R/4.0.4/lib/R/site-library/RcppParallel/include' -I/usr/local/include   -fpic  -g -O2  -c PCRE2/pcre2_error.c -o PCRE2/pcre2_error.o
gcc -I"/opt/R/4.0.4/lib/R/include" -DNDEBUG -DRCPP_USE_UNWIND_PROTECT -I.  -DPCRE2_CODE_UNIT_WIDTH=8 -DHAVE_CONFIG_H -IPCRE2 -mavx2 -msse3 -msse2 -I'/opt/R/4.0.4/lib/R/site-library/Rcpp/include' -I'/opt/R/4.0.4/lib/R/site-library/RcppParallel/include' -I/usr/local/include   -fpic  -g -O2  -c PCRE2/pcre2_extuni.c -o PCRE2/pcre2_extuni.o
gcc -I"/opt/R/4.0.4/lib/R/include" -DNDEBUG -DRCPP_USE_UNWIND_PROTECT -I.  -DPCRE2_CODE_UNIT_WIDTH=8 -DHAVE_CONFIG_H -IPCRE2 -mavx2 -msse3 -msse2 -I'/opt/R/4.0.4/lib/R/site-library/Rcpp/include' -I'/opt/R/4.0.4/lib/R/site-library/RcppParallel/include' -I/usr/local/include   -fpic  -g -O2  -c PCRE2/pcre2_find_bracket.c -o PCRE2/pcre2_find_bracket.o
gcc -I"/opt/R/4.0.4/lib/R/include" -DNDEBUG -DRCPP_USE_UNWIND_PROTECT -I.  -DPCRE2_CODE_UNIT_WIDTH=8 -DHAVE_CONFIG_H -IPCRE2 -mavx2 -msse3 -msse2 -I'/opt/R/4.0.4/lib/R/site-library/Rcpp/include' -I'/opt/R/4.0.4/lib/R/site-library/RcppParallel/include' -I/usr/local/include   -fpic  -g -O2  -c PCRE2/pcre2_jit_compile.c -o PCRE2/pcre2_jit_compile.o
gcc -I"/opt/R/4.0.4/lib/R/include" -DNDEBUG -DRCPP_USE_UNWIND_PROTECT -I.  -DPCRE2_CODE_UNIT_WIDTH=8 -DHAVE_CONFIG_H -IPCRE2 -mavx2 -msse3 -msse2 -I'/opt/R/4.0.4/lib/R/site-library/Rcpp/include' -I'/opt/R/4.0.4/lib/R/site-library/RcppParallel/include' -I/usr/local/include   -fpic  -g -O2  -c PCRE2/pcre2_maketables.c -o PCRE2/pcre2_maketables.o
gcc -I"/opt/R/4.0.4/lib/R/include" -DNDEBUG -DRCPP_USE_UNWIND_PROTECT -I.  -DPCRE2_CODE_UNIT_WIDTH=8 -DHAVE_CONFIG_H -IPCRE2 -mavx2 -msse3 -msse2 -I'/opt/R/4.0.4/lib/R/site-library/Rcpp/include' -I'/opt/R/4.0.4/lib/R/site-library/RcppParallel/include' -I/usr/local/include   -fpic  -g -O2  -c PCRE2/pcre2_match.c -o PCRE2/pcre2_match.o
gcc -I"/opt/R/4.0.4/lib/R/include" -DNDEBUG -DRCPP_USE_UNWIND_PROTECT -I.  -DPCRE2_CODE_UNIT_WIDTH=8 -DHAVE_CONFIG_H -IPCRE2 -mavx2 -msse3 -msse2 -I'/opt/R/4.0.4/lib/R/site-library/Rcpp/include' -I'/opt/R/4.0.4/lib/R/site-library/RcppParallel/include' -I/usr/local/include   -fpic  -g -O2  -c PCRE2/pcre2_match_data.c -o PCRE2/pcre2_match_data.o
gcc -I"/opt/R/4.0.4/lib/R/include" -DNDEBUG -DRCPP_USE_UNWIND_PROTECT -I.  -DPCRE2_CODE_UNIT_WIDTH=8 -DHAVE_CONFIG_H -IPCRE2 -mavx2 -msse3 -msse2 -I'/opt/R/4.0.4/lib/R/site-library/Rcpp/include' -I'/opt/R/4.0.4/lib/R/site-library/RcppParallel/include' -I/usr/local/include   -fpic  -g -O2  -c PCRE2/pcre2_newline.c -o PCRE2/pcre2_newline.o
gcc -I"/opt/R/4.0.4/lib/R/include" -DNDEBUG -DRCPP_USE_UNWIND_PROTECT -I.  -DPCRE2_CODE_UNIT_WIDTH=8 -DHAVE_CONFIG_H -IPCRE2 -mavx2 -msse3 -msse2 -I'/opt/R/4.0.4/lib/R/site-library/Rcpp/include' -I'/opt/R/4.0.4/lib/R/site-library/RcppParallel/include' -I/usr/local/include   -fpic  -g -O2  -c PCRE2/pcre2_ord2utf.c -o PCRE2/pcre2_ord2utf.o
gcc -I"/opt/R/4.0.4/lib/R/include" -DNDEBUG -DRCPP_USE_UNWIND_PROTECT -I.  -DPCRE2_CODE_UNIT_WIDTH=8 -DHAVE_CONFIG_H -IPCRE2 -mavx2 -msse3 -msse2 -I'/opt/R/4.0.4/lib/R/site-library/Rcpp/include' -I'/opt/R/4.0.4/lib/R/site-library/RcppParallel/include' -I/usr/local/include   -fpic  -g -O2  -c PCRE2/pcre2_pattern_info.c -o PCRE2/pcre2_pattern_info.o
gcc -I"/opt/R/4.0.4/lib/R/include" -DNDEBUG -DRCPP_USE_UNWIND_PROTECT -I.  -DPCRE2_CODE_UNIT_WIDTH=8 -DHAVE_CONFIG_H -IPCRE2 -mavx2 -msse3 -msse2 -I'/opt/R/4.0.4/lib/R/site-library/Rcpp/include' -I'/opt/R/4.0.4/lib/R/site-library/RcppParallel/include' -I/usr/local/include   -fpic  -g -O2  -c PCRE2/pcre2_script_run.c -o PCRE2/pcre2_script_run.o
gcc -I"/opt/R/4.0.4/lib/R/include" -DNDEBUG -DRCPP_USE_UNWIND_PROTECT -I.  -DPCRE2_CODE_UNIT_WIDTH=8 -DHAVE_CONFIG_H -IPCRE2 -mavx2 -msse3 -msse2 -I'/opt/R/4.0.4/lib/R/site-library/Rcpp/include' -I'/opt/R/4.0.4/lib/R/site-library/RcppParallel/include' -I/usr/local/include   -fpic  -g -O2  -c PCRE2/pcre2_serialize.c -o PCRE2/pcre2_serialize.o
gcc -I"/opt/R/4.0.4/lib/R/include" -DNDEBUG -DRCPP_USE_UNWIND_PROTECT -I.  -DPCRE2_CODE_UNIT_WIDTH=8 -DHAVE_CONFIG_H -IPCRE2 -mavx2 -msse3 -msse2 -I'/opt/R/4.0.4/lib/R/site-library/Rcpp/include' -I'/opt/R/4.0.4/lib/R/site-library/RcppParallel/include' -I/usr/local/include   -fpic  -g -O2  -c PCRE2/pcre2_string_utils.c -o PCRE2/pcre2_string_utils.o
gcc -I"/opt/R/4.0.4/lib/R/include" -DNDEBUG -DRCPP_USE_UNWIND_PROTECT -I.  -DPCRE2_CODE_UNIT_WIDTH=8 -DHAVE_CONFIG_H -IPCRE2 -mavx2 -msse3 -msse2 -I'/opt/R/4.0.4/lib/R/site-library/Rcpp/include' -I'/opt/R/4.0.4/lib/R/site-library/RcppParallel/include' -I/usr/local/include   -fpic  -g -O2  -c PCRE2/pcre2_study.c -o PCRE2/pcre2_study.o
gcc -I"/opt/R/4.0.4/lib/R/include" -DNDEBUG -DRCPP_USE_UNWIND_PROTECT -I.  -DPCRE2_CODE_UNIT_WIDTH=8 -DHAVE_CONFIG_H -IPCRE2 -mavx2 -msse3 -msse2 -I'/opt/R/4.0.4/lib/R/site-library/Rcpp/include' -I'/opt/R/4.0.4/lib/R/site-library/RcppParallel/include' -I/usr/local/include   -fpic  -g -O2  -c PCRE2/pcre2_substitute.c -o PCRE2/pcre2_substitute.o
gcc -I"/opt/R/4.0.4/lib/R/include" -DNDEBUG -DRCPP_USE_UNWIND_PROTECT -I.  -DPCRE2_CODE_UNIT_WIDTH=8 -DHAVE_CONFIG_H -IPCRE2 -mavx2 -msse3 -msse2 -I'/opt/R/4.0.4/lib/R/site-library/Rcpp/include' -I'/opt/R/4.0.4/lib/R/site-library/RcppParallel/include' -I/usr/local/include   -fpic  -g -O2  -c PCRE2/pcre2_substring.c -o PCRE2/pcre2_substring.o
gcc -I"/opt/R/4.0.4/lib/R/include" -DNDEBUG -DRCPP_USE_UNWIND_PROTECT -I.  -DPCRE2_CODE_UNIT_WIDTH=8 -DHAVE_CONFIG_H -IPCRE2 -mavx2 -msse3 -msse2 -I'/opt/R/4.0.4/lib/R/site-library/Rcpp/include' -I'/opt/R/4.0.4/lib/R/site-library/RcppParallel/include' -I/usr/local/include   -fpic  -g -O2  -c PCRE2/pcre2_tables.c -o PCRE2/pcre2_tables.o
gcc -I"/opt/R/4.0.4/lib/R/include" -DNDEBUG -DRCPP_USE_UNWIND_PROTECT -I.  -DPCRE2_CODE_UNIT_WIDTH=8 -DHAVE_CONFIG_H -IPCRE2 -mavx2 -msse3 -msse2 -I'/opt/R/4.0.4/lib/R/site-library/Rcpp/include' -I'/opt/R/4.0.4/lib/R/site-library/RcppParallel/include' -I/usr/local/include   -fpic  -g -O2  -c PCRE2/pcre2_ucd.c -o PCRE2/pcre2_ucd.o
gcc -I"/opt/R/4.0.4/lib/R/include" -DNDEBUG -DRCPP_USE_UNWIND_PROTECT -I.  -DPCRE2_CODE_UNIT_WIDTH=8 -DHAVE_CONFIG_H -IPCRE2 -mavx2 -msse3 -msse2 -I'/opt/R/4.0.4/lib/R/site-library/Rcpp/include' -I'/opt/R/4.0.4/lib/R/site-library/RcppParallel/include' -I/usr/local/include   -fpic  -g -O2  -c PCRE2/pcre2_valid_utf.c -o PCRE2/pcre2_valid_utf.o
gcc -I"/opt/R/4.0.4/lib/R/include" -DNDEBUG -DRCPP_USE_UNWIND_PROTECT -I.  -DPCRE2_CODE_UNIT_WIDTH=8 -DHAVE_CONFIG_H -IPCRE2 -mavx2 -msse3 -msse2 -I'/opt/R/4.0.4/lib/R/site-library/Rcpp/include' -I'/opt/R/4.0.4/lib/R/site-library/RcppParallel/include' -I/usr/local/include   -fpic  -g -O2  -c PCRE2/pcre2_xclass.c -o PCRE2/pcre2_xclass.o
ar rcs libSFPCRE2.a PCRE2/pcre2_chartables.o PCRE2/pcre2_auto_possess.o PCRE2/pcre2_compile.o PCRE2/pcre2_config.o PCRE2/pcre2_context.o PCRE2/pcre2_convert.o PCRE2/pcre2_dfa_match.o PCRE2/pcre2_error.o PCRE2/pcre2_extuni.o PCRE2/pcre2_find_bracket.o PCRE2/pcre2_jit_compile.o PCRE2/pcre2_maketables.o PCRE2/pcre2_match.o PCRE2/pcre2_match_data.o PCRE2/pcre2_newline.o PCRE2/pcre2_ord2utf.o PCRE2/pcre2_pattern_info.o PCRE2/pcre2_script_run.o PCRE2/pcre2_serialize.o PCRE2/pcre2_string_utils.o PCRE2/pcre2_study.o PCRE2/pcre2_substitute.o PCRE2/pcre2_substring.o PCRE2/pcre2_tables.o PCRE2/pcre2_ucd.o PCRE2/pcre2_valid_utf.o PCRE2/pcre2_xclass.o
Error : RStudio not running
Error : RStudio not running
g++ -std=gnu++11 -shared -L/opt/R/4.0.4/lib/R/lib -L/usr/local/lib -o stringfish.so RcppExports.o sf_functions.o -lpthread -L. -lSFPCRE2 Recording full session info into the projects sesionInfoLog file...  -L"/opt/R/4.0.4/lib/R/lib" -lR; \
  g++ -std=gnu++11 -shared -L"/opt/R/4.0.4/lib/R/lib" -L/usr/local/lib -o stringfish.so RcppExports.o sf_functions.o -lpthread -L. -lSFPCRE2 Recording full session info into the projects sesionInfoLog file... -L/opt/R/4.0.4/lib/R/lib -lR
** R
** inst
** byte-compile and prepare package for lazy loading
Error : RStudio not running
** help
*** installing help indices
  converting help for package ‘stringfish’
    finding HTML links ... done
    convert_to_sf                           html
    get_string_type                         html
    materialize                             html
    random_strings                          html
    sf_assign                               html
    sf_collapse                             html
    sf_compare                              html
    sf_concat                               html
    sf_ends                                 html
    sf_grepl                                html
    sf_gsub                                 html
    sf_iconv                                html
    sf_match                                html
    sf_nchar                                html
    sf_paste                                html
    sf_readLines                            html
    sf_split                                html
    sf_starts                               html
    sf_substr                               html
    sf_tolower                              html
    sf_toupper                              html
    sf_trim                                 html
    sf_vector                               html
    sf_writeLines                           html
    string_identical                        html
** building package indices
Error : RStudio not running
** installing vignettes
** testing if installed package can be loaded from temporary location
Error: package or namespace load failed for ‘stringfish’ in library.dynam(lib, package, package.lib):
 shared object ‘stringfish.so’ not found
Error: loading failed
Execution halted
ERROR: loading failed
* removing ‘/home/user/R/x86_64-pc-linux-gnu-library/4.0.4/stringfish’

The downloaded source packages are in
        ‘/tmp/RtmpSpXoIz/downloaded_packages’
Warning message:
In install.packages("stringfish", type = "source", configure.args = "--with-simd=AVX2") :
  installation of package ‘stringfish’ had non-zero exit status

**Comment by traversc** [comment]
The first error:

> Error : RStudio not running

This package doesn't make any rstudio api calls, so I'm guessing some version issue with package dependencies or a configuration issue on your computer. Try to update the following:

Rcpp, RcppParallel, knitr, rmarkdown, usethis

I would also consider not using Microsoft R, since you always get outdated packages from MRAN.

**Comment by traversc** [comment]
> Recording full session info into the projects sesionInfoLog file...

This blog post suggests it could be due to Rprofile file configuration:

https://www.r-bloggers.com/2017/04/r-for-enterprise-understanding-rs-startup-2/

**Comment by MelvinGatMDRC** [comment]
Ah, I see that the latest release of stringfish was 2021-03-13 and the snapshot is from 2021-03-06. Sorry, not sure how I missed that in my earlier check. 

Separately, the snapshot from MRAN is intentional. Otherwise new release can cause backwards compatibility issues in old programs. 

Edit: shouldn't this install work with the earlier version though?

**Comment by MelvinGatMDRC** [comment]
I got the same error after changing the snapshot. 

I did find a solution though I'm not sure why this was necessary for this package and not for any others that I've installed. 

The solution I found was to add a `umask 0007` command to the /etc/rstudio/rsession-profile file. Once I did that, the permissions on the files being created were such that `stringfish` could be installed. 

Like I said, it's unclear why the `stringfish.so` file was being written with different permissions, but that did the trick.

**Comment by traversc** [comment]
( The version on MRAN was an opinion, not relevant to the install issue. )

A normal install shouldn't touch anything to do with rstudio-rprofile, so I consider that an issue with rstudio/configuration not the package.

Glad you got the issue sorted!
