### ISSUE TITLE
How about a `stringfish.nthreads` option

### ISSUE THREAD

**Issue by statquant** [traversc/stringfish#8]
It would be useful to have an option to set `nthreads` globally.
All signatures would then become
```
sf_fun <- function(..., nthreads = getOption("stringfish.nthreads", 1L)) {
 # code
}
```
What do you think ?
Given how easy it is I can probably PR it if you want.

Many thanks

**Comment by traversc** [comment]
Sure, pull requests are welcome! This is something another person requested earlier, so I can see how it would be useful now. Just make sure the default = 1. 

Feel free to add your info to the DESCRIPTION file if you want to.

**Comment by traversc** [comment]
On CRAN now.
