### ISSUE TITLE
Extend stringfish to factors

### ISSUE THREAD

**Issue by statquant** [traversc/stringfish#9]
Hello, I discovered `stringfish` to day and I think it's really great, I am using `qs` all the time so I do not know how I missed it !
The way `stringfish` work on `character` could be extended to factors.
What it does would be applied on `levels`.
Would that make sense ?

**Comment by traversc** [comment]
Currently, I don't think this is a good idea since it would require tinkering with how R works internally. 

Also factors levels are also usually short and would not see much benefit.
